### ISSUE TITLE
Doesn't check continuously

### ISSUE THREAD

**Issue by bcodin** [anbcodes/AlertForWords#1]
Hi
The alert for words is a great extension but after the initial alert, it doesn't alert anymore.

For example if an email came in with a specific subject word that I'm monitoring, I would have to keep refreshing 5 seconds. Can it be set to check for the word on X intervals without refreshing the page?

Thank you.

**Comment by anbcodes** [comment]
Thank you for your issue.

I just added the feature you requested in [version 1.1.1](https://github.com/anbcodes/AlertForWords/releases/tag/v1.1.1). Hopefully, this works for you.
