### ISSUE TITLE
Add audio to the alert?

### ISSUE THREAD

**Issue by SaraEzzatAli** [anbcodes/AlertForWords#2]
Hi @anbcodes , 

Thank you for making the extension, I love it! I just have one idea, have you tried adding a sound to the alert? I have spent way too long trying to do this but couldn't figure it out. I would really appreciate it if you can provide some help :)

**Comment by anbcodes** [comment]
Hey, thanks for the suggestion - I just attempted to implement it. Let me know if that's what you were looking for.

Also, to get the sound to work you need to have clicked on the page; if you don't, Chrome blocks the audio playback.
